language: php

os:
  - linux

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script: vendor/bin/phpunit

sudo: false

notifications:
  email: false
